# Generated by Django 4.2 on 2024-03-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_options_alter_contact_user_from_and_more'),
        ('content', '0006_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentions_posts', to='account.profile', verbose_name='Mentions'),
        ),
    ]
